patterns = {
    '(hello|salut|hola|good (morning|evening)|howdy|greeting|morning|evening) ?[A-z]?|^(hi)|^(hey)': 'greetings',
    "(how are you|how are you doing|are you ok|how it's going|what's up|what's new with you|eyyo|how about you)[?]?": 'start',
    '(goodbye|bye|see y[aAoO]|farewell|take care|adieu)[.!]?': 'bye',
    '(thanks|thank you|appreciate it|thankful|grateful|indebted to you|much obliged|pleasure|my appreciation)[.!]?': 'thanks',
    '(who you are|. about you .|What are u\?)[?!]?': 'about',
    '(what can you do|what you can do|what are your capabilities|tell me your abilities|how can you help|what are your skills)( to help me| me)?': 'skill',
    '(who created you|by whom were you brought .*|who is your creator|who gave birth to you|who can be credited for your creation)[?!]?': 'creation',
    '(what[\sA-z]{1,}|where[\sA-z]{1,}?)(area|place|location|geographical|country|are you from)[?]?': 'location',
    "(^. )?(hate you|dont't like you|don't trust you|you are fake|fuck you|faggot)": 'hate-you',
    r"(you | from you ).*(hate|negative|dislike|disdain|don't love|don't like|don't care).*(me)": 'you-hate-me',
    r"(.*(careless|importa).*(you))|([ ]?lack of[ ]|[ ]?absence[ ]?).*(concern|support|empathy|care)(.*you)|(you).*(careless|care)": 'careless',
    '(tell me a joke|tell me something funny|(ha){2,}|(ja){2,}|h{4,})': 'jokes',
    '(can i ask you|i have a question)[!]?': 'ask',
    "(no i can't|tell me something else|give ( me )?another solution|i can't do it|it's difficult|not realy|i guess not|all i can do now is)": 'no-approach',
    "[i ]?(refuse to answer|don't want to answer|can't answer)": 'not-answering',
    "(my (private|personal|sensitive)? ?(data|info))": 'data',
    r"\b(?=.*what)(?=.*you)(?=.*name).*\b": 'name',
    r"(you[\s\']?)(told me|said|shared|previous|[ ]?already|before|repeated|provided|mentioned|informed|repeat)( that| this| yours)": 'repeat',
    r"\b(you[A-z\'\s]?)\b.*(incorrect|mistake|wrong|false|inaccurate|not accurate|unsound|misguided|untrue)": 'wrong',
    r"\b(you[A-z\'\s]?)\b.*(fool|idiot|stupid|(\bnot\b.*)cognitive|(\bnot\b.*)smart|dumb|naive|trivial)": 'stupid',
    '(why are you asking|why you are asking)': 'ask-for-asking',
    r".*(you).*(earl|previous|prior|said|mention|say|wrote)": 'contextual-testing',
    r"(how do you feel|how you feel|what is your emotion|your feeling|your emotion)": 'bot-feeling'
}